name:                circuitRouting
version:             0.1.0.0
github:              "wuerges/circuitRouting"
license:             BSD3
author:              "Emilio Wuerges"
maintainer:          "wuerges@gmail.com"
copyright:           "2019 Emilio Wuerges"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wuerges/circuitRouting#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  circuitRouting-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - circuitRouting

tests:
  circuitRouting-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - circuitRouting
